### ISSUE TITLE
Save A Lot (US) (grocery store chain)

### ISSUE THREAD

**Issue by davidhicks** [alltheplaces/alltheplaces#6086]
### Brand name

Save A Lot

### Store finder url(s)

Sending `{"address":"new york"}` to `https://savealot.com/wp-json/locator/v1/address_search/`

Returns:
```
{"formatted_address":"New York, NY, USA","latitude":40.7127753,"longitude":-74.0059728}
```

The store locator then queries (GET, no body):
```
https://savealot.com/wp-json/locator/v1/search/40.71/-74.01/40.1/-75.63/41.32/-72.39/
```

Changing `40` to `39` in the query URL returns blank, so perhaps there is a limit to the bounding box/radius used.

**Comment by tif-calin** [comment]
It seems the boundary is always 49. The route works like:

```
https://savealot.com/wp-json/locator/v1/search/{lat1}/{lng1}/{lat2}/{lng2}/{lat3}/{lng3}

where:
 - lat/lng1: the search coords
 - lat/lng2: the far SE corner of the box to search
 - lat/lng3: the far NW corner of the box to search
```

But the results are either boundaries or there's a limit of 50 stores. You could technically try doing a bunch of queries for every possible block of coordinates using the knowledge of the [most NW and SE coordinates of the US](http://www.cohp.org/extremes/extreme_points.html). But if the limit is by results then you wouldn't know how far to move your next coordinates in a reliable way.

There was once a different API that looked like:
```
http://savealot.shoplocal.com/SaveALot/Entry/LandingContent?storeid=2649877
```

I found it from looking through GitHub scrapers. But this site is now offline (but [archived](https://web.archive.org/web/20240000000000*/savealot.shoplocal.com))
